/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizationRouteRouteImport } from './routes/authorization/route'

const AuthorizationRouteRoute = AuthorizationRouteRouteImport.update({
  id: '/authorization',
  path: '/authorization',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/authorization': typeof AuthorizationRouteRoute
}
export interface FileRoutesByTo {
  '/authorization': typeof AuthorizationRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/authorization': typeof AuthorizationRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/authorization'
  fileRoutesByTo: FileRoutesByTo
  to: '/authorization'
  id: '__root__' | '/authorization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthorizationRouteRoute: typeof AuthorizationRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authorization': {
      id: '/authorization'
      path: '/authorization'
      fullPath: '/authorization'
      preLoaderRoute: typeof AuthorizationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthorizationRouteRoute: AuthorizationRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
